server:
  port: 8080
spring:
  application:
    name: discovery-server
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
  client:
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka
    fetch-registry: true
    register-with-eureka: false

