server:
  port: 8080
spring:
  application:
    name: discovery-server
eureka:
  instance:
    instance-id: app1
  server:
#    enable-self-preservation: false
  client:
    serviceUrl:
          defaultZone: http://localhost:8080/eureka/
    fetch-registry: false
    register-with-eureka: false

