server:
  port: 8081
spring:
  application:
    name: config-server
  cloud:
    config:
      fail-fast: false
#      label:
#      profile:
      server:
        git:
          uri:
          username:
          password:
      discovery:
        enabled: true



eureka:
#  instance:
#    lease-renewal-interval-in-seconds: 2
#    instance-id: app2
  client:
    serviceUrl:
          defaultZone: http://localhost:8080/eureka/
#    register-with-eureka: false
#logging:
#  level:
#    root: debug

